// Code generated by OpenTelemetry Weaver. DO NOT EDIT.
//
// Source: infra/otel/semconv/registry — see README.md.

package semconv

import "go.opentelemetry.io/otel/attribute"

const (
	SchemaURL         = "https://webitel.com/schemas/0.1.0"
	UpstreamSchemaURL = "https://opentelemetry.io/schemas/1.30.0"

	// Namespace prefixes every convention that is ours rather than upstream.
	Namespace = "webitel"
)

// Webitel Database Client.
const (
	// Client address - domain name if available without reverse DNS lookup; otherwise, IP address or Unix domain socket name.
	ClientAddressKey = attribute.Key("client.address")
	// Client port number.
	ClientPortKey = attribute.Key("client.port")
	// The name of a collection (table, container) within the database.
	DBCollectionNameKey = attribute.Key("db.collection.name")
	// The number of queries included in a batch operation.
	DBOperationBatchSizeKey = attribute.Key("db.operation.batch.size")
	// A database operation parameter, with `<key>` being the parameter name, and the attribute value being a string representation of the parameter value.
	DBOperationParameterKey = attribute.Key("db.operation.parameter")
	// The database query being executed.
	DBQueryTextKey = attribute.Key("db.query.text")
	// Number of rows returned by the operation.
	DBResponseReturnedRowsKey = attribute.Key("db.response.returned_rows")
	// Database response status code.
	DBResponseStatusCodeKey = attribute.Key("db.response.status_code")
	// The database management system (DBMS) product as identified by the client instrumentation.
	DBSystemNameKey = attribute.Key("db.system.name")
	// The name of the prepared statement.
	WebitelDBPrepareStmtNameKey = attribute.Key("webitel.db.prepare_stmt.name")
	// The database user the connection authenticates as.
	WebitelDBUserKey = attribute.Key("webitel.db.user")
)

// Webitel Resource.
const (
	// The string ID of the service instance.
	ServiceInstanceIDKey = attribute.Key("service.instance.id")
	// Logical name of the service.
	ServiceNameKey = attribute.Key("service.name")
	// A namespace for `service.name`.
	ServiceNamespaceKey = attribute.Key("service.namespace")
	// The version string of the service API or implementation. The format is not defined by these conventions.
	ServiceVersionKey = attribute.Key("service.version")
)

// Webitel RPC.
const (
	// The [numeric status code](https://github.com/grpc/grpc/blob/v1.33.2/doc/statuscodes.md) of the gRPC request.
	RPCGRPCStatusCodeKey = attribute.Key("rpc.grpc.status_code")
	// Compressed size of the message in bytes.
	RPCMessageCompressedSizeKey = attribute.Key("rpc.message.compressed_size")
	// MUST be calculated as two different counters starting from `1` one for sent messages and one for received message.
	RPCMessageIDKey = attribute.Key("rpc.message.id")
	// Whether this is a received or sent message.
	RPCMessageTypeKey = attribute.Key("rpc.message.type")
	// Uncompressed size of the message in bytes.
	RPCMessageUncompressedSizeKey = attribute.Key("rpc.message.uncompressed_size")
	// The name of the (logical) method being called, must be equal to the $method part in the span name.
	RPCMethodKey = attribute.Key("rpc.method")
	// The full (logical) name of the service being called, including its package name, if applicable.
	RPCServiceKey = attribute.Key("rpc.service")
	// A string identifying the remoting system. See below for a list of well-known identifiers.
	RPCSystemKey = attribute.Key("rpc.system")
)

// Values for db.system.name.
var (
	DBSystemNamePostgresql = DBSystemNameKey.String("postgresql")
)

// Values for rpc.system.
var (
	RPCSystemGRPC = RPCSystemKey.String("grpc")
)
