// Code generated by "stringer -type=EtagType"; DO NOT EDIT.

package etag

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoType-0]
	_ = x[EtagCase-1]
	_ = x[EtagCaseComment-2]
	_ = x[EtagCaseLink-3]
	_ = x[EtagRelatedCase-4]
	_ = x[EtagCaseCommunication-5]
	_ = x[EtagKbArticle-6]
	_ = x[EtagContact-7]
	_ = x[EtagContactName-8]
	_ = x[EtagContactLabel-9]
	_ = x[EtagContactEmail-10]
	_ = x[EtagContactPhone-11]
	_ = x[EtagContactGroup-12]
	_ = x[EtagContactAddress-13]
	_ = x[EtagContactManager-14]
	_ = x[EtagContactComment-15]
	_ = x[EtagContactVariable-16]
	_ = x[EtagContactLanguage-17]
	_ = x[EtagContactTimezone-18]
	_ = x[EtagContactIMClient-19]
	_ = x[EtagSpace-20]
	_ = x[EtagArticle-21]
}

const _EtagType_name = "NoTypeEtagCaseEtagCaseCommentEtagCaseLinkEtagRelatedCaseEtagCaseCommunicationEtagKbArticleEtagContactEtagContactNameEtagContactLabelEtagContactEmailEtagContactPhoneEtagContactGroupEtagContactAddressEtagContactManagerEtagContactCommentEtagContactVariableEtagContactLanguageEtagContactTimezoneEtagContactIMClientEtagSpaceEtagArticle"

var _EtagType_index = [...]uint16{0, 6, 14, 29, 41, 56, 77, 90, 101, 116, 132, 148, 164, 180, 198, 216, 234, 253, 272, 291, 310, 319, 330}

func (i EtagType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_EtagType_index)-1 {
		return "EtagType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EtagType_name[_EtagType_index[idx]:_EtagType_index[idx+1]]
}
