// Code generated by "stringer -type=EtagType"; DO NOT EDIT.

package etag

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoType-0]
	_ = x[EtagCase-1]
	_ = x[EtagCaseComment-2]
	_ = x[EtagCaseLink-3]
}

const _EtagType_name = "NoTypeEtagCaseEtagCaseCommentEtagCaseLink"

var _EtagType_index = [...]uint8{0, 6, 14, 29, 41}

func (i EtagType) String() string {
	if i >= EtagType(len(_EtagType_index)-1) {
		return "EtagType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EtagType_name[_EtagType_index[i]:_EtagType_index[i+1]]
}
